# Generated by Django 4.1.7 on 2023-03-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
