# Generated by Django 4.1.7 on 2023-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_categories_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='blog',
        ),
        migrations.AddField(
            model_name='categories',
            name='blog',
            field=models.ManyToManyField(related_name='category', to='blog.blog'),
        ),
    ]
